<a href="https://colab.research.google.com/github/abhishekanand04/ML-Adv-Supervised-Alogorithms/blob/mladv/kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 !wget "https://drive.google.com/uc?export=download&id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W" -O E-commerce.csv

--2025-06-02 17:27:22--  https://drive.google.com/uc?export=download&id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W
Resolving drive.google.com (drive.google.com)... 74.125.137.102, 74.125.137.138, 74.125.137.101, ...
Connecting to drive.google.com (drive.google.com)|74.125.137.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W&export=download [following]
--2025-06-02 17:27:22--  https://drive.usercontent.google.com/download?id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.2.132, 2607:f8b0:4023:c0d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139827 (137K) [application/octet-stream]
Saving to: ‘E-commerce.csv’

E-commerce.csv      100%[===================>] 136.55K  --.-KB/s    in 0.04s

2025-06-02 17:27:25 (3.35 MB/s) - ‘E-commerce.csv’ saved [139827/139827]

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('./E-commerce.csv')
df.head()

,ID,n_clicks,n_visits,amount_spent,amount_discount,days_since_registration,profile_information
0,1476,130,65,213.905831,31.600751,233,235
1,1535,543,46,639.223004,5.689175,228,170
2,1807,520,102,1157.402763,844.321606,247,409
3,1727,702,83,1195.903634,850.041757,148,200
4,1324,221,84,180.754616,64.283300,243,259

In [ ]:
X=df.drop("ID",axis=1)

In [ ]:
X.describe()

,n_clicks,n_visits,amount_spent,amount_discount,days_since_registration,profile_information
count,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,408.68000,94.475600,1445.090745,388.508637,200.973600,201.040400
std,186.41409,38.866356,1167.663473,487.143968,99.136618,100.139213
min,50.00000,10.000000,0.000000,0.000000,0.000000,0.000000
25%,274.75000,67.000000,609.618538,56.298615,130.000000,132.000000
50%,378.00000,92.000000,1036.189112,137.454623,200.000000,201.000000
75%,522.00000,119.000000,1949.270949,679.540536,268.000000,270.000000
max,1246.00000,259.000000,6567.402267,2428.406527,514.000000,585.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X)
X=scaler.transform(X)

In [ ]:
from sklearn.cluster import KMeans

k = 10 ## arbitrary value
kmeans = KMeans(n_clusters=k,random_state = 42)
z = kmeans.fit_predict(X)

In [ ]:
X.shape

(2500, 6)

In [ ]:
z

array([4, 1, 4, ..., 4, 3, 0], dtype=int32)

In [ ]:
kmeans.cluster_centers_

array([[0.446244  , 0.45801312, 0.2167286 , 0.47023959, 0.5915758 ,
        0.352798  ],
       [0.28474786, 0.32732488, 0.09816583, 0.06147802, 0.3767396 ,
        0.17733822],
       [0.47497704, 0.56495412, 0.19878781, 0.42886582, 0.27856293,
        0.46233559],
       [0.164664  , 0.21314122, 0.4711039 , 0.03134112, 0.20159252,
        0.42403736],
       [0.27571247, 0.32418123, 0.10434311, 0.0681049 , 0.41815641,
        0.50425424],
       [0.42994904, 0.38745458, 0.23028773, 0.49754379, 0.2653048 ,
        0.20471306],
       [0.26584913, 0.33556448, 0.10645962, 0.05564884, 0.65361003,
        0.3124723 ],
       [0.16630765, 0.26322238, 0.51217956, 0.03464402, 0.40089912,
        0.19395432],
       [0.30089555, 0.29727271, 0.10035785, 0.05919501, 0.14587372,
        0.36661008],
       [0.17380965, 0.22304271, 0.51761247, 0.03422794, 0.55037446,
        0.47168459]])

In [ ]:
kmeans.cluster_centers_.shape

(10, 6)